baseurl = "https://siddhartha-gadgil.github.io/automating-mathematics/"
title = "Artificial Intelligence and Mathematics"
copyright = "Copyright &copy; 2018 - Siddhartha Gadgil"
canonifyurls = true
theme = "hyde"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
publishDir = "docs"

[author]
    name = "Siddhartha Gadgil"
    email="siddhartha.gadgil@gmail.com"
    github = "siddhartha-gadgil"
    gitlab = "siddhartha.gadgil"
    linkedin = ""
    facebook = ""
    twitter = "SidGadgil"
    instagram = ""

[params]
    tagline = "towards Automating Mathematics"
